[package]
name = "rsw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.5", features = ["derive"] }
serde = "1.0.133"
serde_derive = "1.0.133"
toml = "0.5.8"
